### ISSUE TITLE
Source Code Missing

### ISSUE THREAD

**Issue by ankita-kalra** [Kiwoo/KazuaNet#5]
The source code was to be uploaded by end of September, it is not uploaded until now.

**Comment by Kiwoo** [comment]
Hi Ankita,

Right after completing KazuaNet work, I needed to prepare my qualifying
exam for Ph.D. thesis.
I will soon take exam on next Tuesday and resume working on it.

Sorry for being late.

Hope you understand.
Kiwoo

**Comment by overfitover** [comment]
I have some questions for your PIXOR. Such as,
w, h, l, y, z, x, yaw = bbox[8:15], but kitti give label is h w l x y z
 Could you open the issue?

**Comment by Kiwoo** [comment]
Dear overfitover,

I am not an author of PIXOR.
And also, I don't understand your question exactly.

Sorry about that.

Kiwoo
